version: '3'

services:

  app:
    build:
      context: ./node
      # recupera o Dockerfile default
    image: marcelogarcia/node:prod
    container_name: app
    # na versao 3 do compose, app nao espera db ficar totalmente disponivel
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s /docker-entrypoint.sh
    networks:
      - nginxWithNode
    tty: true
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
    image: marcelogarcia/nginx:prod
    container_name: nginx
    networks:
      - nginxWithNode
    tty: true
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - mysql_data:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginxWithNode

networks:
  nginxWithNode:
    driver: bridge

volumes:
  mysql_data: